### ISSUE TITLE
Fix bug with wakes and audio player

### ISSUE THREAD

**Issue by hils124** [axis7818/Waypoint#55]
<img width="1094" alt="screen shot 2017-11-03 at 3 54 58 pm" src="https://user-images.githubusercontent.com/13054027/32398954-aae694a8-c0af-11e7-8b9d-352ace2cfcba.png">
![img_2017](https://user-images.githubusercontent.com/13054027/32398955-acefcc1a-c0af-11e7-8dfa-3713f7107e57.PNG)

**Comment by hils124** [comment]
![img_2017](https://user-images.githubusercontent.com/13054027/32398979-d431ce40-c0af-11e7-9a77-21e01c192334.PNG)

**Comment by hils124** [comment]
<img width="966" alt="screen shot 2017-11-03 at 4 04 29 pm" src="https://user-images.githubusercontent.com/13054027/32399106-c049259e-c0b0-11e7-90b2-5ce3ebae2997.png">

**Comment by axis7818** [comment]
looks like I'm opening the shader files each time a wake is made which is likely contributing to the number of open file descriptors. Adding all the sounds on top of that might be too much to handle. I'll fix how shaders are loaded.

**Comment by hils124** [comment]
Fixed with https://github.com/adamcichy/SwiftySound
